name: Günlük Hacim Kuruması Taraması
on:
  schedule:
    - cron: '0 17 * * 5' # Cuma 20:00 TSİ
  workflow_dispatch: # Elle başlatma butonu
jobs:
  run-scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - run: pip install pandas yfinance mplfinance requests
      - run: python hacim_kurumasi.py
