name: Manuel Hacim Analizi (WMA)
on:
  workflow_dispatch:
jobs:
  run-analiz:
    runs-on: ubuntu-latest
    steps:
      - name: Kodu Cek
        uses: actions/checkout@v3

      - name: Python Kur
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Kutuphaneleri Kur
        run: |
          python -m pip install --upgrade pip
          pip install yfinance pandas requests mplfinance pandas_ta

      - name: Dosya Kontrol ve Calistir
        run: |
          ls -la # Klasördeki dosyaları listele (Hata ayıklama için)
          python hacim_analiz.py
