 name: Hisse Fiyat Botu

on:
  schedule:
    # Türkiye saatiyle 10:10 (UTC 07:10)
    - cron: '10 7 * * 1-5'
    # Türkiye saatiyle 13:10 (UTC 10:10)
    - cron: '10 10 * * 1-5'
    # Türkiye saatiyle 18:10 (UTC 15:10)
    - cron: '10 15 * * 1-5'
  workflow_dispatch: 
jobs:
  run-bot:
    runs-on: ubuntu-latest
    steps:
      - name: Kodlari cek
        uses: actions/checkout@v3

      - name: Python ayarla
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Kutuphaneleri kur 
        run: pip install yfinance pandas requests mplfinance


      - name: Botu calistir
        run: python borsa.py

      - name: Degisiklikleri kaydet
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add fiyat_gecmisi.csv
          git commit -m "Fiyat guncellendi" || exit 0
          git push
