name: Borsa Takip Otomasyonu

on:
  schedule:
    # Türkiye Saati 10:30 (UTC 07:30)
    - cron: '30 7 * * *'
    # Türkiye Saati 13:30 (UTC 10:30)
    - cron: '30 10 * * *'
    # Türkiye Saati 18:30 (UTC 15:30)
    - cron: '30 15 * * *'
  workflow_dispatch: # El ile başlatma butonu

jobs:
  run-bot:
    runs-on: ubuntu-latest
    steps:
      - name: Kodu Cek
        uses: actions/checkout@v3

      - name: Python Kur
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Kutuphaneleri Yukle
        run: |
          pip install yfinance pandas requests mplfinance

      - name: Botu Calistir
        run: python borsa_botu.py
