name: Borsa Takip Otomasyonu

on:
  schedule:
    # TSİ 10:30 -> UTC 07:30
    # TSİ 13:30 -> UTC 10:30
    # TSİ 18:30 -> UTC 15:30
    # TSİ 22:00 -> UTC 19:00
    - cron: '30 7,10,15 * * 1-5'
    - cron: '0 19 * * 1-5'
  workflow_dispatch:


jobs:
  run-bot:
    runs-on: ubuntu-latest
    steps:
      - name: Kodu Cek
        uses: actions/checkout@v3

      - name: Python Kur
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Kutuphaneleri Yukle
        run: pip install yfinance pandas requests mplfinance

      - name: Botu Calistir
        run: python bot.py
