name: MG-Hisse Otomatik Tarama

on:
  workflow_dispatch: 
  schedule:
    - cron: '0 5 * * 1-5' # Hafta içi her gün 08:00 TSİ

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Kodları Al
        uses: actions/checkout@v3

      - name: Python Kur
        uses: actions/setup-python@v4
        with:
          python-version: '3.11' # Hata almamak için 3.11 idealdir

      - name: Kütüphaneleri Yükle
        run: |
          python -m pip install --upgrade pip
          pip install pandas requests
          pip install pandas_ta --upgrade
          pip install git+https://github.com/suzit/tvdatafeed.git

      - name: Analizi Başlat
        run: python mg_hisse_tarama.py
